---
title: 'Games of Chance'
subtitle: 'A series of games utilising the Random package'
output: 
  html_document: 
    code_folding: show
    highlight: textmate
    number_sections: yes
    theme: yeti
    toc: yes
---

# Games of Chance

## About

A series of simple games of chance, executed by calling the respective functions directly. Note that I have not included any error checking as for this purpose of this exercise I am assuming the function calls would actually be executed by an interface with constrained inputs.

## Define the variables

Here we establish the global variables for the project, and load any packages needed

```{python init_vars}
#--INITIALISE--#
import random
denomination = 'chips'
wallet = 100
```

## Define utility functions

Here we establish functions that will be used only by other functions.

The print_result function outputs the result of any game function, adding information about the player's remaining balance. Although it's only a single line of code, I chose to make it a utility function so I can change the layout of the output display in one place.

```{python def_gen_func}
#--DEFINE UTILITY FUNCTIONS--#
def print_result(result):
    # Output result
    print(result + '\n\nYou have ' + str(wallet) + ' ' + denomination + ' left.')
```

## Define the games

### Coin Toss

The Coin Toss game takes a pot (the amount the player bets) as an integer and a call as either heads or tails. The game then calculates the result of the coin toss. If the player correctly guessed the result, they win, adding the value of the pot to their wallet. Otherwise they lose, subtracting the value of the pot from their wallet.

1. The two possible call values are assigned to a list called **outcomes** so that we can (using *list*.index) view the call as either a string or an integer
2. Assign a random int between 0 and 1 for the result of the **toss** (heads and tails respectively)
3. Find the string version of the **toss** result by using the **toss** result as the index for returning a value from the **outcomes** list
4. Enter a *try except* to avoid invalid input errors
    1. Convert the original **call** value to an integer by looking up the string value in the **outcomes** list and returning it's position (with *list*.index), lower-casing the input to allow any casing version (heads, Heads, HEADS)
    2. Process the result of the game...
        1. Populate the **result** value based on comparing **toss** to **call**
        2. Adjust the **wallet** *global* variable by the pot accordingly
    3. Pass the **result** of the game to the **print_result** function to display it
5. Print relevant error on *except*

```{python def_coin_toss}
#--DEFINE GAME FUNCTIONS--#
# Coin Toss
def coin_toss(pot, call):
    # Define variables
    global wallet
    outcomes = ['heads', 'tails']
    toss = random.randint(0,1)
    toss_string = outcomes[toss]
    
    # Find result
    try:
      # Convert call to an int
      call = outcomes.index(call.lower())
      
      if call == toss:
          result = toss_string + '\n\nYou guessed correctly!\n\nYou won ' + str(pot) + ' ' + denomination + '!'
          wallet += pot
      else:
          result = toss_string + '\n\nYou guessed incorrectly.\n\nYou lost ' + str(pot) + ' ' + denomination + '.'
          wallet -= pot
      
      # Output result
      print_result(result)
      
    except TypeError:
      # Occurs when user provides a POT value that is not a number
      print('Oops, that wasn''t a valid entry for "pot"')
    
    except ValueError:
      # Occurs when user provides a CALL value that is not 'heads' or 'tails'
      print('Oops, that wasn''t a valid entry for "call"')
    
    except:
      print("Unexpected error:", sys.exc_info()[0])
```    

### Cho Han

The Cho Han game takes a pot (the amount the player bets) as an integer and a call as either even or odd. The game then picks two random numbers and adds them together, to get a number if that is either odd or even. If the player correctly guesses whether the number would be odd or even, they win, adding the value of the pot to their wallet. Otherwise they lose, subtracting the value of the pot from their wallet.

1. The two possible call values are assigned to a list called **outcomes** so that we can (using *list*.index) view the call as either a string or an integer
2. Assign a random int between 0 and 1 for the result of the **roll** (even and odd respectively)
3. Find the string version of the **roll** result by using the **roll** result as the index for returning a value from the **outcomes** list
4. Convert the original **call** value to an integer by looking up the string value in the **outcomes** list and returning it's position (with *list*.index)
5. Enter a *try except* to avoid invalid input errors
    1. Convert the original **call** value to an integer by looking up the string value in the **outcomes** list and returning it's position (with *list*.index), lower-casing the input to allow any casing version (odd, Odd, ODD)
    2. Process the result of the game...
        1. Populate the **result** value based on comparing **roll** to **call**
        2. Adjust the **wallet** *global* variable by the pot accordingly
    3. Pass the **result** of the game to the **print_result** function to display it
6. Print relevant error on *except*

```{python def_cho-han}
# Cho-Han
def cho_han(pot, call):
    # Define variables
    global wallet
    outcomes = ['even', 'odd']
    roll = random.randint(1,6) + random.randint(1,6)
    roll_type = roll % 2
    roll_string = outcomes[roll_type]

    # Find result
    try:
      # Convert call to an int
      call = outcomes.index(call.lower())
      
      if call == roll_type:
          result = str(roll) + '... ' + roll_string + '\n\nYou guessed correctly!\n\nYou won ' + str(pot) + ' ' + denomination + '!'
          wallet += pot
      else:
          result = str(roll) + '... ' + roll_string + '\n\nYou guessed incorrectly.\n\nYou lost ' + str(pot) + ' ' + denomination + '.'
          wallet -= pot
      
      # Output result
      print_result(result)
      
    except TypeError:
      # Occurs when user provides a POT value that is not a number
      print('Oops, that wasn''t a valid entry for "pot"')
    
    except ValueError:
      # Occurs when user provides a CALL value that is not 'heads' or 'tails'
      print('Oops, that wasn''t a valid entry for "call"')
    
    except:
      print("Unexpected error:", sys.exc_info()[0])
```

### Card Draw

The Card Draw game takes only the pot (the amount the player bets.) The game calculates two numbers, one for the player and another for the game. If the player's number is higher they win, adding the value of the pot to their wallet. If it is the same as the game's number they draw and neither win or lose any money. If the player's number is lower than the game's number the player loses, subtracting the value of the pot from their wallet.

1. Assign random numbers to the **player_card** and **game_card** variables
2. Prepare the first part of the **result text**, as this will be the same regardless
3. Enter a *try except* to avoid invalid input errors
    1. Process the result of the game...
        1. Populate the **result** value based on comparing **player_card** to **game_card**
        2. Adjust the **wallet** *global* variable by the pot accordingly
    2. Pass the **result** of the game to the **print_result** function to display it
4. Print relevant error on *except*

```{python def_card_draw}
# Card Draw
def card_draw(pot):
  # Define variables
  global wallet
  player_card = random.randint(1,10)
  game_card = random.randint(1,10)
  result = 'You drew ' + str(player_card) + ' and I drew ' + str(game_card) + '.\n\n'
  
  # Find result
  try:
    if player_card > game_card:
      result += 'You win!\n\nYou won ' + str(pot) + ' ' + denomination + '.'
      wallet += pot
    elif player_card < game_card:
      result += 'I won!\n\nYou lost ' + str(pot) + ' ' + denomination + '.'
      wallet -= pot
    else:
      result += 'We drew.\n\nYou didn''t win or lose.'
    
    # Output result
    print_result(result)
    
  except TypeError:
    # Occurs when user provides a POT value that is not a number
    print('Oops, that wasn''t a valid entry for "pot"')
  
  except:
    print("Unexpected error:", sys.exc_info()[0])
```

### Simple Roulette

The Simple Roulette game takes the pot (the amount the player bets,) the call type (which can either be 'parity' or 'number',) and the call (which is either 'odd'/'even', '00', or a number as a string.) The game calculates the result of a **spin**, returning the number as a string (because 00 and 0 are the same number when defined as ints.) The game then also checks the parity of the **spin**. 

If the player chose 'parity', and their **call** was the same as the parity of the **spin**, or if they chose 'number' and the number of their call was the same as the **spin**, they win, adding the value of the **pot** to their **wallet.** If the player's guess was incorrect the player loses, subtracting the value of the **pot** from their **wallet.**

1. Define a *list* containing all possible **outcomes** of a spin as strings  (because 00 and 0 are the same number when defined as ints)
2. Find the result of the spin by returning a random value from the **outcomes** *list*
3. Find the *spin_parity* of the spin
4. Enter a *try except* to avoid invalid input errors
    1. In roulette a bet against a number returns the pot multiplied by 35, against parity it returns the bet multiplied by 1. Update the **pot** accordingly
    2. Check for specific input errors, printing an error message if needed
    3. Process the result of the game...
        1. Populate the **result** value based on comparing **call** to **spin** or **spin_parity**
        2. Adjust the **wallet** *global* variable by the pot accordingly
        3. Pass the **result** of the game to the **print_result** function to display it
5. Print relevant error on *except*

```{python def_simple_roulette}
# Simple Roulette
def simple_roulette(pot, call_type, call):
  # Define variables
  global wallet
  outcomes = ['0', '00', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28']
  call_types = ['number', 'parity']
  spin = outcomes[random.randint(0, len(outcomes) - 1)]
  if int(spin) == 0 or int(spin) % 2 != 0:
    spin_parity = 'odd'
  else:
    spin_parity = 'even'
  
  try:
    # Set pot value
    if call_type == 'number': pot *= 35
    
    # Find and handle errors
    if call_type.lower() not in call_types:
      print('Oops, call type must be either parity or number.')
    elif call_type.lower() == 'parity' and call.lower() not in ['odd', 'even']:
      print('Oops, parity must be either odd or even.')
    elif call_type.lower() == 'number' and call not in outcomes:
      print('Oops, number must be one of these (as a string): 0, 00, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 19, 20, 21, 22, 23, 24, 25, 26, 27, or 28')
    
    # And without errors, find results 
    elif (call_type == 'parity' and call == spin_parity) or (call_type == 'number' and call == spin):
      result = spin + ', ' + spin_parity + '.\n\nYou guessed correctly!\n\nYou won ' + str(pot) + ' ' + denomination + '.'
      wallet += pot
      print_result(result)
    else:
      result = spin + ', ' + spin_parity + '.\n\nYou guessed incorrectly.\n\nYou lost ' + str(pot) + ' ' + denomination + '.'
      wallet -= pot
      print_result(result)
  
  except TypeError:
    print('Oops, pot needs to be a number')
  
  except AttributeError: 
    print('Oops, call type needs to be a string')
  
  except:
    print("Unexpected error:", sys.exc_info()[0])
    
```

## Play the games!

### The Coin Toss game

Call the game!

```{python call_coin_toss}
#--CALL GAMES--#
# Coin Toss
coin_toss(2, 'Heads')
```

### The Cho-Han game

Call the game!

```{python call_cho-han}
# Cho-Han
cho_han(20, 'odd')
```

### The Card Draw game

Call the game!

```{python card_draw}
# Card Draw
card_draw(20)
```

### Th Simple Roulette Game

Call the game!

#### With a parity call type

```{python simple_roulette-parity}
# Simple Roulette
simple_roulette(20, 'parity', 'odd')
```

#### With a number call type

```{python simple_roulette-number}
# Simple Roulette
simple_roulette(20, 'number', '1')
```